services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: always # Thêm dòng này
    environment:
      VERSION: "2016"
      USERNAME: "Dev"
      PASSWORD: "@1U2I3o4p"
      RAM_SIZE: "12G"
      CPU_CORES: "8"
      DISK_SIZE: "50G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
